apiVersion: v1
kind: Pod
metadata:
  name: carbon14
  namespace: front-end
spec:
  containers:
  - name: carbon14
    image: carbon14
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: c14port
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon14-deploy
  namespace: front-end
  labels:
    app: carbon14
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carbon14
  template:
    metadata:
      labels:
        app: carbon14
    spec:
      containers:
        - name: carbon14
          image: carbon14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: c14port
---
apiVersion: v1
kind: Service
metadata:
  name: carbon14
  namespace: front-end
spec:
  type: NodePort
  selector:
    app: carbon14
  ports:
    - name: carbon14port
      protocol: TCP
      port: 80
      targetPort: c14port
